"""shot model_override

Revision ID: 642681883a9d
Revises: 0bb3ccfe10bf
Create Date: 2026-07-10 17:45:24.788435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642681883a9d'
down_revision: Union[str, Sequence[str], None] = '0bb3ccfe10bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='' so the NOT NULL column can be added to tables that
    # already contain shots — the ORM-side default only applies to new rows.
    with op.batch_alter_table('video_shots', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('model_override', sa.String(length=300), nullable=False, server_default='')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_shots', schema=None) as batch_op:
        batch_op.drop_column('model_override')

    # ### end Alembic commands ###
