"""initial schema

Revision ID: f7bfcb47c327
Revises: 
Create Date: 2026-06-18 02:10:35.864854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bfcb47c327'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_kind', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('output_kind', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('reference_asset_ids_json', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_model', sa.String(length=120), nullable=False),
    sa.Column('provider_job_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('result_path', sa.String(length=500), nullable=False),
    sa.Column('result_asset_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_kind', sa.String(length=20), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=80), nullable=False),
    sa.Column('public_token', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['generation_job_id'], ['asset_generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_public_token'), ['public_token'], unique=True)

    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('visual_identity', sa.Text(), nullable=False),
    sa.Column('default_disclosure_text', sa.String(length=200), nullable=False),
    sa.Column('default_voice_provider', sa.String(length=40), nullable=False),
    sa.Column('elevenlabs_voice_id', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('end_card_bg_color', sa.String(length=9), nullable=False),
    sa.Column('end_card_text_color', sa.String(length=9), nullable=False),
    sa.Column('default_cta_text', sa.String(length=280), nullable=False),
    sa.Column('default_disclosure_text', sa.String(length=200), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=False),
    sa.Column('logo_public_token', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_kits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_kits_logo_public_token'), ['logo_public_token'], unique=False)

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visual_identity', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_script', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cta_text', sa.String(length=280), nullable=False),
    sa.Column('caption_style', sa.String(length=40), nullable=False),
    sa.Column('include_disclosure', sa.Boolean(), nullable=False),
    sa.Column('disclosure_text', sa.String(length=200), nullable=False),
    sa.Column('creative_direction', sa.Text(), nullable=False),
    sa.Column('voiceover_source', sa.String(length=20), nullable=False),
    sa.Column('voiceover_upload_path', sa.String(length=500), nullable=False),
    sa.Column('music_upload_path', sa.String(length=500), nullable=False),
    sa.Column('music_volume', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('generated_plan_json', sa.JSON(), nullable=True),
    sa.Column('primary_avatar_id', sa.Integer(), nullable=True),
    sa.Column('brand_kit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_kit_id'], ['brand_kits.id'], ),
    sa.ForeignKeyConstraint(['primary_avatar_id'], ['avatars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_cast_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_kind', sa.String(length=20), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('request_summary_json', sa.JSON(), nullable=True),
    sa.Column('response_summary_json', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('final_video_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=False),
    sa.Column('render_log', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('share_token', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renders_share_token'), ['share_token'], unique=True)

    op.create_table('video_shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('shot_order', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('reference_asset_ids_json', sa.JSON(), nullable=True),
    sa.Column('reference_strategy', sa.String(length=30), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=False),
    sa.Column('camera_direction', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_model', sa.String(length=120), nullable=False),
    sa.Column('provider_job_id', sa.String(length=200), nullable=False),
    sa.Column('polling_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('clip_path', sa.String(length=500), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_shots')
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renders_share_token'))

    op.drop_table('renders')
    op.drop_table('provider_logs')
    op.drop_table('project_cast_members')
    op.drop_table('video_projects')
    op.drop_table('ingredients')
    with op.batch_alter_table('brand_kits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_kits_logo_public_token'))

    op.drop_table('brand_kits')
    op.drop_table('avatars')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_public_token'))

    op.drop_table('assets')
    op.drop_table('asset_generation_jobs')
    # ### end Alembic commands ###
